---
name: deploy-book

on:
  workflow_call:
  workflow_dispatch:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
    paths:
      - "book/**"

permissions:
  contents: write

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # init project
      - name: Init project
        run: |
          pipx install copier>=7.0.0
          make init-project-force

      # Build the book
      - name: Build the book
        run: |
          pip install -r book/requirements.txt
          jupyter-book build book

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html
