---
name: deploy-mkdocs
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "mkdocs.yaml"
      - "docs/**.md"
      - "docs/images/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # install copier
      - name: Install copier
        run: pipx install copier>=7.0.0

      # init project
      - name: Init project
        run: make init-project-force

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force
