---
name: lint

#############################
# Start the job on all push #
#############################
on:
  workflow_call:
  workflow_dispatch:
  # push:
  #   branches-ignore: [main]
  #   # Remove the line above to run when pushing to main
  pull_request:
    branches: main

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: lint-code-base
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # install poetry
      - name: Install poetry
        run: pipx install poetry>=1.3.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      # install dependencies
      - name: Install dependencies for linters
        run: make install-linters

      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          make lint
