---
name: pipeline-prelease

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  call-test-workflow:
    name: Test
    uses: ./.github/workflows/ci-test.yaml
  call-prerelease-workflow:
    name: Pre-release
    needs:
      - call-test-workflow
    uses: ./.github/workflows/cd-prerelease.yaml
    secrets: inherit
