---
name: semantic-release-test

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    # Name the Job
    name: semantic-release-test
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # install copier and init project
      - name: Install copier and init project
        if: github.repository == 'entelecheia/hyperfast-python-template'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          pipx install copier>=7.0.0
          make reinit-project-force

      # set env variable
      - name: Set env variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # install poetry
      - name: Install poetry
        run: pipx install poetry>=1.3.2

      # install dependencies
      - name: Install dependencies
        run: make install-dev

      - name: Python Semantic Release to PyPI
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          poetry run semantic-release publish --noop --verbosity=DEBUG --define=branch=${{ env.BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
